### ISSUE TITLE
Feedback request

### ISSUE THREAD

**Issue by d1g** [Gubaer/josm-contourmerge-plugin#11]
Please confirm if current page covers all features: https://josm.openstreetmap.de/wiki/Help/Plugin/ContourMerge

What else should be stated or shown?

**Comment by Gubaer** [comment]
When I look at the screen animations included in the [help page](https://josm.openstreetmap.de/wiki/Help/Plugin/ContourMerge), it is difficult for me to identify the individual steps in the workflow: What is the first step to do? What to do next? What is the result? On my computer and in my browser the animation (the animated GIF) is running too fast. 

My mother tongue isn't english but I feel  that the help text should be proofread by a native speaker. What's your mother tongue?

**Comment by d1g** [comment]
> What is the first step to do? What to do next? What is the result?

Aha, valid point, you have to pause video/gifs, but there no possibility to do this at trac AFAIK.

http://stackoverflow.com/a/16572160
https://github.com/buzzfeed/libgif-js
http://slbkbs.org/jsgif/

Cutting GIF in multiple stages may/will work, but this will take _additional time_. I want to have at least quick demo (visual demo, not just text like it was before my edits)

> My mother tongue isn't english but I feel that the help text should be proofread by a native speaker. What's your mother tongue? 

Руский родной. My written English is far from perfect (I guess, you may see trivial errors in programs like Word) and I'm focusing on links, paragraphs and cross-links more than on fluent text, slight re-write will help native speakers to read text without cringe. 


Problem with _too many instructions_ is that page will bloat to the point nobody would read it: 
https://josm.openstreetmap.de/wiki/Help/Action/Upload - I wrote "In simple words" section to help readers
https://josm.openstreetmap.de/wiki/Help/Action/Draw

Another con is that it takes time to write them, but if reader able to capture general idea, he could repeat it without every step (as if there were no documentation at all).

**Comment by Gubaer** [comment]
> Aha, valid point, you have to pause video/gifs, but there no possibility to do this at trac AFAIK.

Ah, I understand. Indeed, there is no "player" functionality on the trac page. It is not possible to start/stop/pause the animated GIF.

> Cutting GIF in multiple stages may/will work, but this will take additional time.

It's great you already tried to create the animated. If you find time you could even create a video and publish it on youtube. I once tried to do so, see [this youtube video](https://www.youtube.com/watch?v=eREgLuuKhpc)

> Problem with too many instructions is that page will bloat to the point nobody would read it: 
> https://josm.openstreetmap.de/wiki/Help/Action/Upload - I wrote "In simple words" section to help readers

Ты поймал меня ;-) Несколько лет назад я написал этот текст. Я сагласен - у него слишком много подробностей. Но в то время нужно было описывать новые фичи, которые каждому пользователю сейчас уже известные.
