### ISSUE TITLE
Regression: Cut-nodes are not highlighted after 12712

### ISSUE THREAD

**Issue by mkyral** [Gubaer/josm-contourmerge-plugin#14]
In current latest (12870), the contourmerge tool does not show a yellow cross on cut-nodes. It works in tested (12712). Plugin still works, but nodes, that splits polygons to parts, are not highlighted.

![obrazek](https://user-images.githubusercontent.com/155542/30523581-1698e8e0-9be4-11e7-831f-2ed1878ecc77.png)

See https://josm.openstreetmap.de/ticket/15318 for details.

**Comment by Gubaer** [comment]
Published a new release of the plugin. Please update it from the JOSM property dialog.
