### ISSUE TITLE
Mouse cursor changes in other modes

### ISSUE THREAD

**Issue by SammysHP** [Gubaer/josm-contourmerge-plugin#16]
Even if the contourmerge tool is not active the mouse cursor will change to a version with a yellow cross when hovering on nodes.

JOSM 13938
contourmerge 1032

**Comment by Gubaer** [comment]
thanks for reporting! I'll look into it next week, when I'll be back from holidays.

**Comment by Gubaer** [comment]
Should be fixed in plugin release 1033. Please update the `contourmerge` plugin in the JOSM preferences dialog.

**Comment by SammysHP** [comment]
Confirmed working in JOSM 13973 and contourmerge 1033, thank you!
