### ISSUE TITLE
No way to assign a keyboard shortcut(?)

### ISSUE THREAD

**Issue by stefanct** [Gubaer/josm-contourmerge-plugin#2]
Hi,

I would love to use the plugin, but i usually dont have the toolbar displayed... adding a hook for a keyboard shortcut would help me a lot (even if it has no default shortcut set).

**Comment by grischard** [comment]
For what it's worth, it is now possible to assign a shortcut to the contourmerge mode. I have no idea what's made this possible, but I've assigned ctrl-M. This ticket can be closed.

**Comment by Gubaer** [comment]
Ok, awesome! This is probably thanks to a change in JOSM itself.
