### ISSUE TITLE
DataIntegrityProblemException: Deleted node referenced

### ISSUE THREAD

**Issue by Gubaer** [Gubaer/josm-contourmerge-plugin#20]
See JOSM issue [#17771](https://josm.openstreetmap.de/ticket/17771)

**Comment by don-vip** [comment]
We also have received [#17044](https://josm.openstreetmap.de/ticket/17044) with this short description:
> _After using Contour-Merge plugin, when I tried to create/move an intermediate node (x) on the merged line_ 
Stacktrace is not identical, I don't know if it's the same issue.
