### ISSUE TITLE
Duplicated way nodes

### ISSUE THREAD

**Issue by GerdP** [Gubaer/josm-contourmerge-plugin#21]
See https://josm.openstreetmap.de/ticket/18365
Hope you can reproduce this.

**Comment by SHARCRASH** [comment]
Any news about the resolution of this bug? It adds work and may put at risk the upload of the entire changeset, i've had a placeholder issue, see here comments 5 & 6: https://josm.openstreetmap.de/ticket/18518

**Comment by Gubaer** [comment]
hi, sorry, for the delay! Here's an update: I'll be working next week on this issue.

**Comment by Gubaer** [comment]
I've published release v1.0.6 of the plugin. It should fix  the issue. Please update the plugin in the JOSM preferences.

**Comment by SHARCRASH** [comment]
I tested a couple of times and did not encounter the issue. Thank you very much! :)
