### ISSUE TITLE
Nodes crossing over

### ISSUE THREAD

**Issue by ggeldenhuis** [Gubaer/josm-contourmerge-plugin#8]
Hi
I get a problem when trying to merge two ways. The points swaps over. I have tried various orders of selection but can't seem to get it to work as I expect. I am attaching a before and after screenshot but will gladly provide more info if required.
![screen shot 2014-01-04 at 15 59 18](https://f.cloud.github.com/assets/192423/1844854/4a1c0bf8-7559-11e3-856f-c1639c281d47.png)
![screen shot 2014-01-04 at 15 54 39](https://f.cloud.github.com/assets/192423/1844855/4cd8dede-7559-11e3-8199-f56e53dfebe1.png)

**Comment by Gubaer** [comment]
This should be fixed in release [v0.1.2](https://github.com/Gubaer/josm-contourmerge-plugin/releases/tag/v0.1.2). Closing. Please reopen if still broken.
